### ISSUE TITLE
SQLite Database Errors happen during the integration tests, but does not affect the final results.

### ISSUE THREAD

**Issue by tromai** [oracle/macaron#106]
**DESCRIPTION**
In the integration tests, at this test case - https://github.com/oracle-samples/macaron/blob/38ddeb8c1061a9a98f36b89efcc3de51f4ab5ffa/scripts/dev_scripts/integration_tests.sh#L218

There is an SQLite Database error - https://github.com/oracle-samples/macaron/actions/runs/4474590474/jobs/7863208199#step:8:7114. It seems that Macaron was attempting to insert a dependency relationship that already exists in the database. This error does not affect the final outcome of the test.
```
Error: -21 01:50:33,316 [ERROR] Database error (sqlite3.IntegrityError) UNIQUE constraint failed: _dependency.dependent_repository, _dependency.dependency_repository 

[SQL: INSERT INTO _dependency (dependent_repository, dependency_repository) VALUES (?, ?)] 

[parameters: (50, 51)] 


(Background on this error at: https://sqlalche.me/e/20/gkpj)
```

**Comment by tromai** [comment]
I have had a look into this and this behavior is expected. 
The dependency table defined in Macaron [here](https://github.com/oracle-samples/macaron/blob/38ddeb8c1061a9a98f36b89efcc3de51f4ab5ffa/src/macaron/database/table_definitions.py#L35) has a UNIQUE constraint on both fields. This table records the repository ID of both dependent and dependency. 
Therefore, if we run Macaron multiple times, the same relationship is INSERTED to this table which cause the duplicated entry error as described above. However, this does not affect the final result of the analysis.
A better way to identify a repository target could prevent such situation - https://github.com/oracle-samples/macaron/issues/33

**Comment by behnazh-w** [comment]
Completed via https://github.com/oracle/macaron/pull/305
