### ISSUE TITLE
Support running the analysis with the SBOM without having to provide the repo path

### ISSUE THREAD

**Issue by tromai** [oracle/macaron#108]
**Description**
This ticket is created to track the enhancement for running the analysis given an SBOM.
At the moment, Macaron needs to have the git URL of the main repo or the config file as an entry point to the analysis. In some cases, we don't have the git URL to begin with or we cannot access the main target repository because it's behind authentication wall, etc. 
In those cases, it's very important that we:
- Could extract the necessary information about the main target from the given SBOM without having to provide the git URL beforehand.
- If the main target cannot be accessed we reflect it in the reports and keep on analyzing the dependencies.

**Blocking**

- [x] #95 
- [x] #157
- [x] #162

**Comment by behnazh-w** [comment]
We should break this into two PRs. 

- One for handling the case where the main target repo is not provided via `-rp` or `-c`, in which case we should still properly analyze the dependencies and the main target results (not available) should be reflected in the reports.
- A separate PR can take care of the case where we need to resolve the main target repository through the SBOM itself.

**Comment by tromai** [comment]
Sounds good to me. I will create another 2 GH issues and link it to this main issue.

**Comment by behnazh-w** [comment]
We can remove https://github.com/oracle/macaron/issues/158 from tasks in this issue and track that separately.

**Comment by tromai** [comment]
Thanks @behnazh-w I close this issue.
