### ISSUE TITLE
Allow disabling a check

### ISSUE THREAD

**Issue by behnazh-w** [oracle/macaron#133]
- [ ] We need to allow a list of checks to be disabled from the CLI and handle it properly in the report.
- [ ] Add an option to disable all the default checks.

**Comment by tromai** [comment]
By `default checks` do you mean the current checks that currently come along with Macaron (e.g. `build_as_code`)?

**Comment by behnazh-w** [comment]
> By `default checks` do you mean the current checks that currently come along with Macaron (e.g. `build_as_code`)?

Yes. In future when we allow loading external checks this would be useful.
