### ISSUE TITLE
Macaron does not identify npm provenance publish

### ISSUE THREAD

**Issue by joycebrum** [oracle/macaron#358]
First of all, thanks for developing this amazing tool! It is being extremely useful.

Considering that now that SLSA provenance is officially supported by the npm ecosystem, it is possible to publish both artifact and provenance by using: 

```
npm publish --provenance
```

Example: https://github.com/joycebrum/dummy-project/blob/main/.github/workflows/release.yml

And it appears as a "provenance summary" in the npm page:

![image](https://github.com/oracle/macaron/assets/22223372/bad48dea-8459-44d5-b201-7d6eb3fc7f5a)

But it seems that macaron does not identify this scenario, neither the build script nor the npm publish command:

![image](https://github.com/oracle/macaron/assets/22223372/284d2090-e3ac-4031-9db8-36939a693c65)

It would be nice if this scenario is also identified by Macaron.

**Comment by behnazh-w** [comment]
Thanks @joycebrum for trying out Macaron and reporting this issue. We definitely plan to discover provenances generated by `npm publish --provenance` on GitHub Actions. You can keep track of the progress in [this milestone](https://github.com/oracle/macaron/milestone/6).

**Comment by behnazh-w** [comment]
Closed via https://github.com/oracle/macaron/issues/365 and  https://github.com/oracle/macaron/pull/639
