### ISSUE TITLE
Use the Python bindings for in-toto/attestation

### ISSUE THREAD

**Issue by behnazh-w** [oracle/macaron#426]
We could possibly use the [in-toto-attestation](https://github.com/in-toto/attestation/tree/858b9917479327f2d1e88a08394a1534ac1f892d/python) package that contains Python bindings for in-toto/attestation to validate the schema.

**Comment by benmss** [comment]
I looked into the library and feel that it is not suitable for our use case. The library exists to properly validate an artifact's provenance, rather than to verify the validity of a given provenance file. From the website for the most relevant method: 

> Performs complete in-toto supply chain verification for a final product. ([Source](https://in-toto.readthedocs.io/en/latest/api.html#supply-chain-verification))
