### ISSUE TITLE
Add build tool GoReleaser

### ISSUE THREAD

**Issue by joycebrum** [oracle/macaron#443]
Currently macaron can identify the SLSA GoReleaser but not the standard GoReleaser.

Test case https://github.com/sigstore/sget: 
[sget_json.txt](https://github.com/oracle/macaron/files/12457275/sget_json.txt)

Expected build script: https://github.com/sigstore/sget/blob/main/.github/workflows/release.yml

It would be good to also identify builds with goreleaser.

**Comment by behnazh-w** [comment]
Thanks for the issue. Currently, we support Go repositories only when they generate SLSA provenances using [the SLSA trusted builder](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_go_slsa3.yml). We need to add support for the Go build tool to be able to support projects that do not generate provenances yet.

We will keep track of this issue in [this milestone](https://github.com/oracle/macaron/milestone/14).

**Comment by behnazh-w** [comment]
Completed via https://github.com/oracle/macaron/pull/451
