### ISSUE TITLE
Urllib3 provenance expectation problem

### ISSUE THREAD

**Issue by benmss** [oracle/macaron#479]
The expectation file urllib3_PASS.cue can fail unexpectedly due to the urllib3 repository sometimes using version branches/tags that start with a `v`. E.g. `v2.0.5`. This can be solved by adding an optional token to the file's uri regular expression string.

**Comment by behnazh-w** [comment]
Thanks for reporting this issue. Unlike the previous releases, [the latest release](https://github.com/urllib3/urllib3/tree/v2.0.5) is using `v` in the tag.
