### ISSUE TITLE
Add a tutorial for the commit finder

### ISSUE THREAD

**Issue by behnazh-w** [oracle/macaron#500]
[urllib3](https://github.com/urllib3/urllib3/releases/tag/2.0.6) generates SLSA provenances as part of its GitHub releases. To demonstrate the Python support in Macaron, we can add a tutorial for urllib3  version v2.0.6, providing a PURL and SBOM as input.

**Comment by benmss** [comment]
Switched to `flask` as `urllib3` does not have dependencies.

**Comment by benmss** [comment]
This tutorial will now be done with the `arrow` library. Its purpose has also been adjusted to focus on demonstrating the capabilities and usage of the commit finder feature.
