### ISSUE TITLE
No dependencies returned when one of multiple build tools fails

### ISSUE THREAD

**Issue by benmss** [oracle/macaron#523]
When an analysis target has multiple build tools, and one of these build tools relates to a dependency analyser that either cannot be found, or is unsupported, Macaron will report no dependencies, thereby potentially discarding legitimate results from the others.

For example, `apache/flink` reveals two build tools: `maven` and `pip`. As `pip` is not supported, the dependencies found for `maven` are not returned and therefore not analysed.

A solution to this problem is to continue analysis when a build tool fails, as long as there is at least one other build tool that succeeds.

**Comment by behnazh-w** [comment]
Closed via https://github.com/oracle/macaron/pull/748
