### ISSUE TITLE
Running git fetch only does not guarantee that we have fetched all changes related to tags

### ISSUE THREAD

**Issue by tromai** [oracle/macaron#547]
# Summary
`git fetch` **will not** fetch the changes of existing tags in the local repository if that tag has been modified in the remote repository. To be able to fetch that modification, we must run `git fetch --force --tags`. 
Note, before git 2.20, running `git fetch --tags` has the same behavior as `git fetch --force --tags` in this scenario ([documentation](https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt-ltrefspecgt)).

# Details
From the [documentation](https://git-scm.com/docs/git-fetch), the default behavior of `git fetch` is:
Fetch branches and/or tags (collectively, "refs") from one or more other repositories, along with the objects necessary to complete their histories. 
```
...
By default, any tag that points into the histories being fetched is also fetched; the effect is to fetch tags that point at branches that you are interested in.
...
When no remote is specified, by default the origin remote will be used, unless there's an upstream branch configured for the current branch.
...
```
With that say, in the context of fetching, when you run `git fetch` , it will fetch new references (e.g. branches) and the objects necessary to complete their histories (commit objects). It will only fetch the tags that points to the new histories or any new tags from the remote repository (even in the case that new tags point to an old commit that already exists).
However, it will not update an existing tag in the local repository if that tag has been modified in the remote repository. By "modified", I mean that someone would do this:
```
git tag --delete existing_tag_name
git tag existing_tag_name <another_new_commit>
git push --force --tags  
```
which essentially modify the commit that the tag `existing_tag_name` is pointing to in the remote repository.
In this case, if you run `git fetch` on the local repository, `existing_tag_name` will not be updated to reflect the modification from the remote repository (however, it will not raise any error, and new commits, new branches, new refs are still being fetched as usual).
To make `existing_tag_name` in the local repository point to `another_new_commit` you must run:
`git fetch --force --tags`
Running `git fetch --tags` only: 1. wouldn't update the modified existing tags, 2. still fetch the new commit history from remote, 3. the command will return an error status code:
```
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 1 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 851 bytes | 851.00 KiB/s, done.
From github.com:tromai/test-repo
   14800f3..58b0069  main       -> origin/main
 ! [rejected]        v1.0.0     -> v1.0.0  (would clobber existing tag)
```
# Solution
We have decided that for now, it's better to use `git fetch --tags --force` to make sure we analyze the most up-to-date version of the repository.

**Comment by behnazh-w** [comment]
I don't think this should be tagged as a bug. What if analyzing an old commit that already exists locally is preferred? This is a decision made by us to force update the tags, but in general it shouldn't be considered as a bug.

**Comment by tromai** [comment]
# Update
After some more testing, I noticed that if a tag were to be deleted in the remote repository, running `git fetch --tags --force` won't delete that tag from the local repository. This behavior is similar to branches, where fetching only gains new branches (that are newly created in remote) but doesn't update deleted branches (in remote) to your local git repository. 
To make git delete any branches or tags from the local repository if they are deleted from remote, we must run `git fetch --tags --force --prune --prune-tags`.
Therefore, we have decided to update the final solution to use `git fetch --tags --force --prune --prune-tags` instead.
