### ISSUE TITLE
One micronaut-test integration test is running with a PURL, but we check for dependency report files.

### ISSUE THREAD

**Issue by tromai** [oracle/macaron#577]
In this integration test case [here](https://github.com/oracle/macaron/blob/1f7f6640ae96791bc47d7083c747c73d6488ef3e/scripts/dev_scripts/integration_tests.sh#L269-L286), we are running the analysis on a PURL without dependency resolving `-purl pkg:maven/io.micronaut/micronaut-test-core@4.1.0 --skip-deps`. However, we check for two dependencies report files `caffeine.json` and `slf4j.json`. 
The reason this test case is still passing is because it's reusing `caffeine.json` and `slf4j.json` from test cases that run before it.

**Comment by behnazh-w** [comment]
That's expected. If dependencies are manually specified in the configuration file, even if the `--skip-deps` is passed, those dependencies will be analyzed. `--skip-deps` only skips analyzing dependencies that are automatically resolved.

**Comment by tromai** [comment]
I agree it would be expected if we are analyzing with a yaml config file. However, because we are providing a PURL, --skip-deps here would mean that at most one software component is analyzed. :thinking:

**Comment by behnazh-w** [comment]
Right, looks like the output comparisons have been mixed up with the test above. I will fix it.

**Comment by tromai** [comment]
I think this test case used to be a config file test case (which explains the different dependency report files checking). In this [PR](https://github.com/oracle/macaron/pull/508), it was changed to use a PURL instead.
