### ISSUE TITLE
Use repository URL provided as input for finding a commit

### ISSUE THREAD

**Issue by behnazh-w** [oracle/macaron#621]
In cases that the repository URL for an artifact is not available, we should allow the user to provide the URL as input and let the commit finder find the commit if the input PURL has a version, e.g.,

```bash
macaron analyze -rp https://github.com/assertj/assertj -purl pkg:maven/org.assertj/assertj.core@3.25.1 --skip-deps
```

Right now we require the user to provide the commit in addition to the URL even though the PURL contains a version:

```bash
[ERROR] Please provide the commit digest for the repo at https://github.com/assertj/assertj that matches to the PURL string pkg:maven/org.assertj/assertj.core@3.25.1.
```

**Comment by behnazh-w** [comment]
I had a typo in the artifact name: `assertj.core` should be `assertj-core`. So, `assertj` is not a good example, but I can imagine other libraries that might have this problem.

**Comment by benmss** [comment]
One example of a project that could benefit from this is Tiny Media Manager. This project stopped releasing on Maven after version 3.0.5 in 2019. Passing Macaron a PURL with a later version, e.g. 4.3.13, would lead to no repository being found.
