### ISSUE TITLE
Check GitHub repository tags via API calls before cloning

### ISSUE THREAD

**Issue by benmss** [oracle/macaron#644]
Currently tags for a GitHub repository are retrieved as part of the repository cloning operation. By using GitHub's API, tags alone can be retrieved, allowing the Commit Finder to perform its function before the repository is cloned. In cases where the Commit Finder would be unable to match a version to a tag and find a commit (meaning analysis will not continue), this allows cloning the repository to be skipped entirely.

**Comment by behnazh-w** [comment]
We should  make sure that other git services and the local clones of repositories work as expected.

**Comment by benmss** [comment]
The potential performance gain for this feature was shown to be low even in the best case scenario, while analysis of many repositories of interest would be slower with it enabled.
