### ISSUE TITLE
Potential problem for commit finder when packages do not use semver.

### ISSUE THREAD

**Issue by jenstroeger** [oracle/macaron#706]
Package versioning in the Python ecosystem doesn’t always follow [semantic versioning](https://semver.org/); in fact, alternative [versioning schemes](https://en.wikipedia.org/wiki/Software_versioning#Schemes) are documented [here](https://packaging.python.org/en/latest/specifications/version-specifiers/#compatibility-with-other-version-schemes).[^1] For example for final release versions,

> The release segment consists of one or more non-negative integer values, separated by dots:
> ```
> N(.N)*
> ```
> Final releases within a project MUST be numbered in a consistently increasing fashion, otherwise automated tools will not be able to upgrade them correctly.

and then

> Date based release segments are also permitted.

For example, [black](https://github.com/psf/black) or [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear) are popular packages following a date based version scheme. It might be interesting to pull metadata of existing packages from the [PyPI API](https://warehouse.pypa.io/api-reference/) and correlate a package’s release date with its version number, and perhaps other non-semver versioning schemes… [^2] 🤔

With that in mind, I suspect the commit finder might need to be reviewed?

[^1]: See also [romantic versioning](https://github.com/romversioning/romver) and [sentimental versioning](https://github.com/dominictarr/sentimental-versioning).

[^2]: Unfortunately, the [current pyproject.toml spec](https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-project-metadata-the-project-table) doesn’t seem to contain a “versioning scheme” entry, so Macaron might be stuck with a few heuristics-based wild-wild guesses…

**Comment by behnazh-w** [comment]
Macaron's commit finder can correctly find the commit for [black](https://github.com/psf/black) and [flake8-bugbear](https://github.com/PyCQA/flake8-bugbear) even though they follow a date-based version pattern. But these versions fail to communicate breaking changes via major version. It would be nice to have a check in Macaron that reports if a project does not follow semantic versioning?

**Comment by jenstroeger** [comment]
@behnazh-w have you tried [`pytz`](https://pythonhosted.org/pytz/) which [supposedly](https://packaging.python.org/en/latest/specifications/version-specifiers/#olson-database-versioning) follows IANA’s timezone versioning ([link](https://github.com/eggert/tz/tags), [docs](https://data.iana.org/time-zones/tz-link.html)) — a year followed by a lower-case letter.

**Comment by behnazh-w** [comment]
> @behnazh-w have you tried [`pytz`](https://pythonhosted.org/pytz/) which [supposedly](https://packaging.python.org/en/latest/specifications/version-specifiers/#olson-database-versioning) follows IANA’s timezone versioning ([link](https://github.com/eggert/tz/tags), [docs](https://data.iana.org/time-zones/tz-link.html)) — a year followed by a lower-case letter.

No I haven't tried this package. @benmss what do you think?

**Comment by jenstroeger** [comment]
> It would be nice to have a check in Macaron that reports if a project does not follow semantic versioning?

That would be useful information in the final report.

If my project depends on packages that don’t programmatically communicate breaking changes then that needs to be considered when declaring my project’s deps. So, if Macaron could alert me to such funky deps, that’d be schnufte indeed.

**Comment by benmss** [comment]
It appears the commit finder does not work with the IANA format currently. Thanks @jenstroeger for bringing this to our attention.

For the `2013.6` and beyond versions it works fine.

**Comment by jenstroeger** [comment]
I suspect that any versioning scheme that follows an incremental, number based approach (see outdated Python [PEP-440](https://peps.python.org/pep-0440/) and beyond) might just work, but arbitrary repos and packages — especially of other language ecosystems — might not. See also [here](https://en.wikipedia.org/wiki/Software_versioning#Schemes).

**Comment by jenstroeger** [comment]
@benmss looks like this issue can be closed?

Did you sample a (large) set of package metadata from PyPI and check what version strings they’re using? For example
```
> curl -s https://pypi.org/pypi/pytz/json | jq '.releases | keys[]'
"2004a"
"2004b"
"2004b.2"
"2004d"
"2005a"
...
```
gives you all [pytz](https://pypi.org/project/pytz/) releases, however, you might have more luck digging through the [Project Metadata Table](https://warehouse.pypa.io/api-reference/bigquery-datasets.html#project-metadata-table).

One more question: https://github.com/oracle/macaron/blob/e8ce555c128cf60ff74b2e384e1415c6556ec669/src/macaron/repo_finder/commit_finder.py#L331-L332 why does that trailing zero receive special treatment?

**Comment by benmss** [comment]
For now only the `pytz` package was tested, as that particular format was triggering a bug. A handful of other Python packages have been tested previously with no issues. Larger scale testing has been done for other languages. Not for Python just yet but it is planned.

> why does that trailing zero receive special treatment?

This is because some versions have one or more additional zeros when compared to their tag.
E.g. Version `1.0.0` vs. Tag `1.0`, or Version `2.0.0` vs Tag `v2`

> It would be nice to have a check in Macaron that reports if a project does not follow semantic versioning?

@behnazh-w @jenstroeger  I have created a new issue for this, and I encourage discussion of that [there](https://github.com/oracle/macaron/issues/728).

**Comment by jenstroeger** [comment]
> This is because some versions have one or more additional zeros when compared to their tag. E.g. Version `1.0.0` vs. Tag `1.0`, or Version `2.0.0` vs Tag `v2`

Hmm 🤔 

I ask because the RHS `len(split) > 2 and split[-1] == "0"` “feels” hacky and fragile to me — what if `split[-1]` is `"000"`?

Instead, I think Python provides interesting iterators[^1] that you can use to compare two version strings for equality (I assume that’s your primary goal). Now let’s assume that a version string is composed of numbers separated by e.g. a `"."` and all prefix and suffix alphanumerical fluff has been stripped. Then
```python
>>> from itertools import zip_longest
>>> 
>>> v = "2.0.0.0"  # A version string.
>>> t = "2"  # A tag string representing a version.
>>> all(int(sv) == int(st) for sv, st in zip_longest(v.split("."), t.split("."), fillvalue="0"))
True
```
compares these two version strings, no matter how many fragments and how zeroes each of the version fragments is made of.

> I have created a new issue for this, and I encourage discussion of that https://github.com/oracle/macaron/issues/728.

Thank you, I’ll take a look.

[^1]: Take a look at the built-in [itertools](https://docs.python.org/3/library/itertools.html) package, and the useful [more-itertools](https://github.com/more-itertools/more-itertools) package.
