### ISSUE TITLE
Add a new tag for tutorial integration tests

### ISSUE THREAD

**Issue by behnazh-w** [oracle/macaron#807]
It would be good to add a new tutorial tag in the integration tests, to make it a convention to add a test for each new tutorial, and easily find them. Once the tag is added, we should update the relevant integration tests and also update the contribution guidelines.

**Comment by tromai** [comment]
> Once the tag is added, we should update the relevant integration tests 
Do you mean updating the test definition of tutorial tests to add this new tag? And not updating the test content (expected results).
