### ISSUE TITLE
The branch of the target component within the JSON report has type `str | None` while other fields of the target info has type `str`

### ISSUE THREAD

**Issue by tromai** [oracle/macaron#832]
In the JSON report generated by Macaron, the `target.info` field contains in formation of the target software component. This is an example of that field (taken from the report generated by this test case - https://github.com/oracle/macaron/blob/3d576b9bf9c0ad92b08dfa2d2e326543868ba37f/tests/integration/cases/micronaut-projects_micronaut-test/test.yaml):
```json
    "info": {
            "full_name": "pkg:github.com/micronaut-projects/micronaut-test@5b81340f319a2287cb2e81ddec0154c0ea2510cf",
            "local_cloned_path": "git_repos/github_com/micronaut-projects/micronaut-test",
            "remote_path": "https://github.com/micronaut-projects/micronaut-test",
            "branch": null,
            "commit_hash": "5b81340f319a2287cb2e81ddec0154c0ea2510cf",
            "commit_date": "2024-01-15T10:27:33+00:00"
        },
```
The information displayed here is recorded at this place in the source code https://github.com/oracle/macaron/blob/f4fd86fc01c7ec17c711301065effb74ec77bef5/src/macaron/slsa_analyzer/analyze_context.py#L245-L257

The value of `branch` in this dictionary is `str | None`. This is because:
- `self.component.repository.branch_name` is of type `str | None`

I wonder if this is intended, or should we use an empty string here to indicate nullness to be consistent with other fields in the `target.info` field.

**Comment by behnazh-w** [comment]
Yes, that's intended. `component.repository.branch_name` can be `None` even if `component.repository` is resolved (is not `None`). However, `commit_hash` and `commit_date` cannot be `None` if `component.repository` is resolved and should always have a `str` value.
