### ISSUE TITLE
Handling Python packages from “other” repositories and artifactories

### ISSUE THREAD

**Issue by jenstroeger** [oracle/macaron#874]
The other day I came across two Python packages that are _not_ hosted on Github or Gitlab:

- the [rfc3987](https://pypi.org/project/rfc3987/) package is hosted [here](https://codeberg.org/atufi/rfc3987) on [Codeberg](https://codeberg.org/) and distributed through PyPI [here](https://pypi.org/project/rfc3987/); and
- the [py3-validate-email](https://git.ksol.io/karolyi/py3-validate-email) package is hosted on a private [Forjego](https://forgejo.org/) server and can be installed only directly from their own site (PyPI removed the package — understandably so — for licensing reasons).

How would Macaron handle these dependencies? Would I manually declare those deps as “un/trusted” and Macaron would skip them? Or are there plans to support other git services, with or without CI?

**Comment by behnazh-w** [comment]
Thank you for raising this issue! Macaron can support these Git services if you manually clone the repository and provide the path using the `--local-repos-path` option. For more details, please refer to the [documentation](https://oracle.github.io/macaron/pages/using.html#analyzing-a-repository-on-the-local-file-system).

However, if the Git service also uses a custom CI service, please note that CI analysis checks in Macaron may not work as expected, and additional support will be needed. You can find a list of currently supported CI services [here](https://oracle.github.io/macaron/pages/supported_technologies/index.html#ci-services).

**Comment by jenstroeger** [comment]
Thank you for elaborating, @behnazh-w, please feel free to close this issue.
